server:
  name: "0.0.0.0"
  port: 7860

defaults:
  setting_threshold: 0.1
  max_keypoints: 2000
  keypoint_threshold: 0.05
  enable_ransac: true
  ransac_method: CV2_USAC_MAGSAC
  ransac_reproj_threshold: 8
  ransac_confidence: 0.9999
  ransac_max_iter: 10000
  ransac_num_samples: 4
  match_threshold: 0.2
  setting_geometry: Homography

matcher_zoo:
  # example config
  Example:
    # show in `Matching Model` or not, default: true
    enable: false
    # matcher name
    matcher: example
    # skip ci or not, default: false
    skip_ci: true
    # dense matcher or not, default: true
    dense: true
    # info
    info:
      # dispaly name in `Matching Model`
      name: example(example)
      # conference/journal/workshop Year
      source: "CVPR XXXX"
      # github link
      github: https://github.com/example/example
      # paper link
      paper: https://arxiv.org/abs/xxxx.xxxx
      # project link
      project: https://example.com
      # show in `support algos` table
      display: false
      # low, medium, high
      efficiency: low

  dad(RoMa):
    matcher: sift-lg
    skip_ci: false
    info:
      name: sift-lg #dispaly name
      source: "ARXIV 2025"
      paper: https://arxiv.org/abs/2503.07347
      github: https://github.com/Parskatt/dad
      display: true
      efficiency: medium  # low, medium, high


retrieval_zoo:
  netvlad:
    enable: true
  openibl:
    enable: true
  cosplace:
    enable: true
